#ifndef CONFIG_H
#define CONFIG_H

#define LED_PIN 13

#define JOYSTICK_X_PIN A0
#define JOYSTICK_Y_PIN A1
#define JOYSTICK_BTN_PIN 2

#define JOYSTICK_TASK_STACK_SIZE 256
#define DISPLAY_TASK_STACK_SIZE 256
#define TASK_PRIORITY 1

#define JOYSTICK_TASK_FREQUENCY_MS 50
#define DISPLAY_TASK_FREQUENCY_MS 500

#define ADC_RESOLUTION 1023.0f
#define VREF 5.0f

#define JOYSTICK_MIN_ANGLE -45.0f
#define JOYSTICK_MAX_ANGLE 45.0f

#endif