#ifndef CONFIG_H
#define CONFIG_H

#define TRIG_PIN 9
#define ECHO_PIN 8
#define LED_PIN 13

#define ULTRASONIC_TASK_STACK_SIZE 128
#define DISPLAY_TASK_STACK_SIZE 128
#define TASK_PRIORITY 1

#define ULTRASONIC_TASK_FREQUENCY_MS 100
#define DISPLAY_TASK_FREQUENCY_MS 500

#define DISTANCE_THRESHOLD_CM 10

#endif